fix: various small epub related fixes
## Description


### resolve path to account for relative paths (mostly dev)  

The check in `getReadaloudFilepath` if the ebook is inside of the asset folder does not know if `<fullpath>/assets/<book>/text/<book>.epub` is in the asset folder if assets dir is a relative path like `../dev-data`.

Stupid case but good to check

###  make uploading singluar epubs work  

Bug in replace asset for epub/readloud, would move a folder with the epub `<book.epub>/<book>.epub` under `/text`. should obv just move the `<book.epub>`.

### dont fail when some epubcreators dont have a value  

I found some books where importing would fail on `getCreators` bc the check for the creator was not accurate or something. This fixes it

Just see the code, there was a case where creator was actually null

This was the error

```
[2026-05-30 23:58:56.810 +0200] WARN: [SCAN:manual] [extract-ebook-manifest] Step extract-ebook-manifest failed for book Kraken (ebook)
    err: {
      "type": "TypeError",
      "message": "Cannot set properties of undefined (setting 'role')",
      "stack":
          TypeError: Cannot set properties of undefined (setting 'role')
              at /Users/thomas/Projects/storyteller.worktrees/tfk-replace-api/web/.next/server/chunks/[root-of-the-server]__0ff835fe._.js:3873:27
              at Array.forEach (<anonymous>)
              at Epub.getCreators (/Users/thomas/Projects/storyteller.worktrees/tfk-replace-api/web/.next/server/chunks/[root-of-the-server]__0ff835fe._.js:3852:18)
```

Changelog-epub: fixed
Changelog-align: fixed
Changelog-web: fixed